namespace RandomPlanetGenerator.Models {
    public class People {
        public static string[] Possibilities = new string[] {
            "humans",
            "intelligent cephalopods",
            "clones of Ronald Reagan",
            "amazonian women",
            "uhh it's racist of you to even ask",
            "sentient rattlesnakes",
            "human supremacists",
            "anti-human robots",
            "humans, but everyone has literally two left feet",
            "dogs",
            "foxes",
            "dogfoxes",
            "teenagers",
            "tumblr users",
            "nerds",
            "androids",
            "pop singers",
            "starks",
            "lannisters",
            "centaurs",
            "victorian children",
            "literal cat people",
            "literal catgirls",
            "telepaths with no sense of privacy",
            "former reality show stars",
            "loose cannon cops with nothing to lose",
            "sentient trees",
            "orphans with no ambition",
            "republicans who have just had enough",
            "hippies who think communism works",
            "allegorical talking animals",
            "character actors whose names you can never quite place but you're sure you saw them in that one thing",
            "six-eyed clams who only open on the solstice",
            "cuttlefish who will not cuddle fish",
            "pandas who remember how to have sex",
            "thinly veiled political statements",
            "those grey area 51 aliens",
            "Anna and Elsa",
            "disney villains",
            "weeaboos",
            "hipsters"
        };
    }
}
